### ISSUE TITLE
Livepeer Hackathon - 6/13/2018 to 6/14/2018

### ISSUE THREAD

**Issue by ericxtang** [livepeer/project-management#40]
Join the June Community Hackathon - https://livepeercommunity.org/hackathon-june

**Open to all**
Participate at our NYC or Berlin workspaces, or join us remotely in the [Discord chat](https://discord.gg/bh9U23).

**Schedule**

1. Share ideas for hack projects here anytime.
2. 10:00am Eastern June 13- video chat to share hack pitch ideas. Of course feel free to start hacking beforehand, but this is a good time to share ideas and team up! - 
meet.google.com/tdv-amns-gns
‎(‪US‬) ‪+1 352-612-0326‬
PIN: ‪128 284 924#‬
3. 5:00pm Eastern June 14 - video chat to show off hacks. - 
meet.google.com/tdv-amns-gns
‎(‪US‬) ‪+1 352-612-0326‬
PIN: ‪128 284 924#‬

**Preparation**

1. Check out [Livepeer Developer Docs](http://livepeer.readthedocs.io/en/latest/developers.html)
2. Check out [LivepeerJS](https://github.com/livepeer/livepeerjs)
3. If you want to develop on Ethereum, check out truffle as a good tool for getting started.

Feel free to post an ideas or ask any questions here.

**Comment by RaffiSapire** [comment]
Ideas:

ENS integration for https://explorer.livepeer.org/transcoders - let transcoders choose their username and campaign URL, and display these on the explorer rather than just their ETH address.

Build your own Livepeer TV - better version of media.livepeer.org that suits a use case you think is important

Mobile staking tool - make it easier for token holders to claim their fees from each daily round, monitor their transcoder. Yondon built an alert tool last time (see outcomes)

Josiah is hacking on finding the best ways to integrate a distributed database into a DApp. So there are tools like HyperDB and IPFS that are easy to play around with for basic examples, but there are not a lot of precedent for them being used widely in applications. We think they are super important for the dapp ecosystem. If you want to be a part of the hack and attempt to find ways to overcome challenges for production ready distributed databases, that's what Josiah is working on and he would love a bunch of people to bounce ideas off of.
