### ISSUE TITLE
WebRTC Support in Livepeer Media Server

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#5]
This is a big item, but popularly requested. Can we support the necessary WebRTC functionality in LPMS like serving as a signaling server, NAT Traversal via STUN/ICE/TURN, etc.

The goal would be low latency, realtime video/audio conferencing on the Livepeer network.

**Comment by dob** [comment]
This library might be worth looking into for incorporation into LPMS: Licode http://lynckia.com/licode/index.html

**Comment by rayj00** [comment]
I also recommend Muaz Kahn's WebRTC open source work at: https://www.webrtc-experiment.com/  as a source of capabilities that are in demand with webrtc.  His RTCMultiConnection.js API is exceptional.

**Comment by backkem** [comment]
We're building a pure Go implementation of WebRTC at [pions/webrtc](https://github.com/pions/webrtc). We currently have working demo's of both the media API and DataChannel API. Once our implementation stabilizes we will likely start contributing support to other projects. However, I wanted to reach out already. Please let us know if you have any specific needs in order to implement WebRTC support down the line. (CC pions/webrtc#52)
